<?php
/**
 * county_ext functions and definitions
 *
 * @package WordPress
 * @subpackage county_ext
 * @since county_ext 1.0
 */

/**
 * Set the content width based on the theme's design and stylesheet.
 *
 * Used to set the width of images and content. Should be equal to the width the theme
 * is designed for, generally via the style.css stylesheet.
 */
if ( ! isset( $content_width ) )
	$content_width = 640;

/** Tell WordPress to run county_ext_setup() when the 'after_setup_theme' hook is run. */
add_action( 'after_setup_theme', 'county_ext_setup' );

if ( ! function_exists( 'county_ext_setup' ) ):
/**
 * Sets up theme defaults and registers support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which runs
 * before the init hook. The init hook is too late for some features, such as indicating
 * support post thumbnails.
 *
 * To override county_ext_setup() in a child theme, add your own county_ext_setup to your child theme's
 * functions.php file.
 *
 * @uses add_theme_support() To add support for post thumbnails and automatic feed links.
 * @uses register_nav_menus() To add support for navigation menus.
 * @uses add_custom_background() To add support for a custom background.
 * @uses add_editor_style() To style the visual editor.
 * @uses load_theme_textdomain() For translation/localization support.
 * @uses set_post_thumbnail_size() To set a custom post thumbnail size.
 *
 * @since county_ext 1.0
 */
function county_ext_setup() {

	add_action( 'wp_print_styles', 'add_ie_style_sheet', 200 );
	function add_ie_style_sheet() {
	    wp_enqueue_style( 'ie7', get_bloginfo('stylesheet_directory') . '/css/ie.css', array(), '1.0' );
	}
 
	add_filter( 'style_loader_tag', 'make_ie_style_sheet_conditional', 10, 2 );
	/**
	 * Add conditional comments around IE style sheet.
	 *
	 * @param string $tag Existing style sheet tag
	 * @param string $handle Name of the enqueued style sheet
	 * @return string Amended markup
	 */
	function make_ie_style_sheet_conditional( $tag, $handle ) {
	    if ( 'ie7' == $handle )
	        $tag = '<!--[if lte IE 7]>' . "\n" . $tag . '<![endif]-->' . "\n";
	    return $tag;
	}

	// This theme styles the visual editor with editor-style.css to match the theme style.
	add_editor_style();

	// This theme uses post thumbnails
	add_theme_support( 'post-thumbnails' );
	// Add new image sizes
	add_image_size('featured',960,9999);
	// Add default posts and comments RSS feed links to head
	add_theme_support( 'automatic-feed-links' );

	// Make theme available for translation
	// Translations can be filed in the /languages/ directory
	load_theme_textdomain( 'county_ext', TEMPLATEPATH . '/languages' );

	$locale = get_locale();
	$locale_file = TEMPLATEPATH . "/languages/$locale.php";
	if ( is_readable( $locale_file ) )
		require_once( $locale_file );

	// This theme uses wp_nav_menu() in one location.
	register_nav_menus( array(
		'primary' => __( 'Primary Navigation', 'county_ext' ),
	) );

	// This theme allows users to set a custom background
	add_custom_background();
	

	// load Slideshow scripts
	function load_js() {
	        // instruction to only load if it is not the admin area
		if ( !is_admin() ) { 
		// register script location with wp_register_script	
	   	wp_register_script('my_jquery',
	       	get_bloginfo('stylesheet_directory') . '/js/my_jquery.js', array('jquery-ui-tabs'));	
	       // enqueue the custom jquery js
	   	wp_enqueue_script('my_jquery');	
		}	         
	}    
	add_action('init', 'load_js');	
	
	function load_cycle_js() {
	        // instruction to only load if it is not the admin area
		if ( !is_admin() ) { 
		// register script location, dependencies and version with wp_register_script	
	   	wp_register_script('cycle',
	       	get_bloginfo('stylesheet_directory') . '/js/jquery.cycle.all.min.js',
	       array('jquery'),
	       '1.4.2' );
	       // enqueue the jQuery scrollTo script
	   	wp_enqueue_script('cycle');	
		}	         
	}    
	add_action('init', 'load_cycle_js');
}	
endif;


/**
 * Makes some changes to the <title> tag, by filtering the output of wp_title().
 *
 * If we have a site description and we're viewing the home page or a blog posts
 * page (when using a static front page), then we will add the site description.
 *
 * If we're viewing a search result, then we're going to recreate the title entirely.
 * We're going to add page numbers to all titles as well, to the middle of a search
 * result title and the end of all other titles.
 *
 * The site title also gets added to all titles.
 *
 * @since county_ext 1.0
 *
 * @param string $title Title generated by wp_title()
 * @param string $separator The separator passed to wp_title(). Twenty Ten uses a
 * 	vertical bar, "|", as a separator in header.php.
 * @return string The new title, ready for the <title> tag.
 */
function county_ext_filter_wp_title( $title, $separator ) {
	// Don't affect wp_title() calls in feeds.
	if ( is_feed() )
		return $title;

	// The $paged global variable contains the page number of a listing of posts.
	// The $page global variable contains the page number of a single post that is paged.
	// We'll display whichever one applies, if we're not looking at the first page.
	global $paged, $page;

	if ( is_search() ) {
		// If we're a search, let's start over:
		$title = sprintf( __( 'Search results for %s', 'county_ext' ), '"' . get_search_query() . '"' );
		// Add a page number if we're on page 2 or more:
		if ( $paged >= 2 )
			$title .= " $separator " . sprintf( __( 'Page %s', 'county_ext' ), $paged );
		// Add the site name to the end:
		$title .= " $separator " . get_bloginfo( 'name', 'display' );
		// We're done. Let's send the new title back to wp_title():
		return $title;
	}

	// Otherwise, let's start by adding the site name to the end:
	$title .= get_bloginfo( 'name', 'display' );

	// If we have a site description and we're on the home/front page, add the description:
	$site_description = get_bloginfo( 'description', 'display' );
	if ( $site_description && ( is_home() || is_front_page() ) )
		$title .= " $separator " . $site_description;

	// Add a page number if necessary:
	if ( $paged >= 2 || $page >= 2 )
		$title .= " $separator " . sprintf( __( 'Page %s', 'county_ext' ), max( $paged, $page ) );

	// Return the new title to wp_title():
	return $title;
}
add_filter( 'wp_title', 'county_ext_filter_wp_title', 10, 2 );

/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 *
 * To override this in a child theme, remove the filter and optionally add
 * your own function tied to the wp_page_menu_args filter hook.
 *
 * @since county_ext 1.0
 */
function county_ext_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}
add_filter( 'wp_page_menu_args', 'county_ext_page_menu_args' );

/**
 * Sets the post excerpt length to 40 characters.
 *
 * To override this length in a child theme, remove the filter and add your own
 * function tied to the excerpt_length filter hook.
 *
 * @since county_ext 1.0
 * @return int
 */
function county_ext_excerpt_length( $length ) {
	return 40;
}
add_filter( 'excerpt_length', 'county_ext_excerpt_length' );

/**
 * Returns a "Continue Reading" link for excerpts
 *
 * @since county_ext 1.0
 * @return string "Continue Reading" link
 */
function county_ext_continue_reading_link() {
	return ' <a href="'. get_permalink() . '">' . __( 'Continue <span class="meta-nav">&rarr;</span>', 'county_ext' ) . '</a>';
}

/**
 * Replaces "[...]" (appended to automatically generated excerpts) with an ellipsis and county_ext_continue_reading_link().
 *
 * To override this in a child theme, remove the filter and add your own
 * function tied to the excerpt_more filter hook.
 *
 * @since county_ext 1.0
 * @return string An ellipsis
 */
function county_ext_auto_excerpt_more( $more ) {
	return ' &hellip;' . county_ext_continue_reading_link();
}
add_filter( 'excerpt_more', 'county_ext_auto_excerpt_more' );

/**
 * Adds a pretty "Continue Reading" link to custom post excerpts.
 *
 * To override this link in a child theme, remove the filter and add your own
 * function tied to the get_the_excerpt filter hook.
 *
 * @since county_ext 1.0
 * @return string Excerpt with a pretty "Continue Reading" link
 */
function county_ext_custom_excerpt_more( $output ) {
	if ( has_excerpt() && ! is_attachment() ) {
		$output .= county_ext_continue_reading_link();
	}
	return $output;
}
add_filter( 'get_the_excerpt', 'county_ext_custom_excerpt_more' );

/**
 * Remove inline styles printed when the gallery shortcode is used.
 *
 * Galleries are styled by the theme in Twenty Ten's style.css.
 *
 * @since county_ext 1.0
 * @return string The gallery style filter, with the styles themselves removed.
 */
function county_ext_remove_gallery_css( $css ) {
	return preg_replace( "#<style type='text/css'>(.*?)</style>#s", '', $css );
}
add_filter( 'gallery_style', 'county_ext_remove_gallery_css' );

if ( ! function_exists( 'county_ext_comment' ) ) :
/**
 * Template for comments and pingbacks.
 *
 * To override this walker in a child theme without modifying the comments template
 * simply create your own county_ext_comment(), and that function will be used instead.
 *
 * Used as a callback by wp_list_comments() for displaying the comments.
 *
 * @since county_ext 1.0
 */
function county_ext_comment( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment;
	switch ( $comment->comment_type ) :
		case '' :
	?>
	<li <?php comment_class(); ?> id="li-comment-<?php comment_ID(); ?>">
		<div id="comment-<?php comment_ID(); ?>">
		<div class="comment-author vcard">
			<?php echo get_avatar( $comment, 40 ); ?>
			<?php printf( __( '%s <span class="says">says:</span>', 'county_ext' ), sprintf( '<cite class="fn">%s</cite>', get_comment_author_link() ) ); ?>
		</div><!-- .comment-author .vcard -->
		<?php if ( $comment->comment_approved == '0' ) : ?>
			<em><?php _e( 'Your comment is awaiting moderation.', 'county_ext' ); ?></em>
			<br />
		<?php endif; ?>

		<div class="comment-meta commentmetadata"><a href="<?php echo esc_url( get_comment_link( $comment->comment_ID ) ); ?>">
			<?php
				/* translators: 1: date, 2: time */
				printf( __( '%1$s at %2$s', 'county_ext' ), get_comment_date(),  get_comment_time() ); ?></a><?php edit_comment_link( __( '(Edit)', 'county_ext' ), ' ' );
			?>
		</div><!-- .comment-meta .commentmetadata -->

		<div class="comment-body"><?php comment_text(); ?></div>

		<div class="reply">
			<?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>
		</div><!-- .reply -->
	</div><!-- #comment-##  -->

	<?php
			break;
		case 'pingback'  :
		case 'trackback' :
	?>
	<li class="post pingback">
		<p><?php _e( 'Pingback:', 'county_ext' ); ?> <?php comment_author_link(); ?><?php edit_comment_link( __('(Edit)', 'county_ext'), ' ' ); ?></p>
	<?php
			break;
	endswitch;
}
endif;

// Custom search 
add_filter('get_search_form', 'custom_search_form');
function custom_search_form() {

	$search_text = get_search_query() ? esc_attr( apply_filters( 'the_search_query', get_search_query() ) ) : apply_filters('county_ext_search_text', esc_attr__('Search', 'county_ext'));
	$button_text = apply_filters( 'county_ext_search_button_text', esc_attr__( 'Go', 'county_ext' ) );

	$onfocus = " onfocus=\"if (this.value == '$search_text') {this.value = '';}\"";
	$onblur = " onblur=\"if (this.value == '') {this.value = '$search_text';}\"";

	$form = '
		<form method="get" class="searchform" action="' . get_option('home') . '/" >
			<input type="text" value="'. $search_text .'" name="s" class="s"'. $onfocus . $onblur .' />
			<input type="submit" class="searchsubmit" value="'. $button_text .'" />
		</form>
	';

	return apply_filters('custom_search_form', $form, $search_text, $button_text);
}

/**
 * Register widgetized areas, including two sidebars and four widget-ready areas in the sidebar.
 *
 * To override county_ext_widgets_init() in a child theme, remove the action hook and add your own
 * function tied to the init hook.
 *
 * @uses register_sidebar
 */
function county_ext_widgets_init() {
	// Area 1, located at the top of the sidebar.
	register_sidebar( array(
		'name' => __( 'Primary Widget Area', 'county_ext' ),
		'id' => 'primary-widget-area',
		'description' => __( 'The primary widget area', 'county_ext' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );

	// Area 2, located in the second sidebar.
	register_sidebar( array(
		'name' => __( 'Aside Widget Area', 'county_ext' ),
		'id' => 'aside-widget-area',
		'description' => __( 'The aside widget area', 'county_ext' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );

	// Area 3, located in the second sidebar.
	register_sidebar( array(
		'name' => __( 'Home Middle #1', 'county_ext' ),
		'id' => 'home-middle-1',
		'description' => __( 'Home Middle #1', 'county_ext' ),
		'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );	

	// Area 4, located in the second sidebar.
	register_sidebar( array(
		'name' => __( 'Home Middle #2', 'county_ext' ),
		'id' => 'home-middle-2',
		'description' => __( 'Home Middle #2', 'county_ext' ),
		'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );		
	
	// Area 5, located in the second sidebar.
	register_sidebar( array(
		'name' => __( 'Home Middle #3', 'county_ext' ),
		'id' => 'home-middle-3',
		'description' => __( 'Home Middle #3', 'county_ext' ),
		'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );
}

/** Register sidebars by running county_ext_widgets_init() on the widgets_init hook. */
add_action( 'widgets_init', 'county_ext_widgets_init' );

/**
 * Removes the default styles that are packaged with the Recent Comments widget.
 *
 * To override this in a child theme, remove the filter and optionally add your own
 * function tied to the widgets_init action hook.
 *
 */
function county_ext_remove_recent_comments_style() {
	global $wp_widget_factory;
	remove_action( 'wp_head', array( $wp_widget_factory->widgets['WP_Widget_Recent_Comments'], 'recent_comments_style' ) );
}
add_action( 'widgets_init', 'county_ext_remove_recent_comments_style' );

if ( ! function_exists( 'county_ext_posted_on' ) ) :
/**
 * Prints HTML with meta information for the current post—date/time and author.
 *
 * @since county_ext 1.0
 */
function county_ext_posted_on() {
	printf( __( '<span class="%1$s">Posted on</span> %2$s <span class="meta-sep">by</span> %3$s', 'county_ext' ),
		'meta-prep meta-prep-author',
		sprintf( '<a href="%1$s" title="%2$s" rel="bookmark"><span class="entry-date">%3$s</span></a>',
			get_permalink(),
			esc_attr( get_the_time() ),
			get_the_date()
		),
		sprintf( '<span class="author vcard"><a class="url fn n" href="%1$s" title="%2$s">%3$s</a></span>',
			get_author_posts_url( get_the_author_meta( 'ID' ) ),
			sprintf( esc_attr__( 'View all posts by %s', 'county_ext' ), get_the_author() ),
			get_the_author()
		)
	);
}
endif;

if ( ! function_exists( 'county_ext_posted_in' ) ) :
/**
 * Prints HTML with meta information for the current post (category, tags and permalink).
 *
 */
function county_ext_posted_in() {
	// Retrieves tag list of current post, separated by commas.
	$tag_list = get_the_tag_list( '', ', ' );
	if ( $tag_list ) {
		$posted_in = __( 'This entry was posted in %1$s and tagged %2$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'county_ext' );
	} elseif ( is_object_in_taxonomy( get_post_type(), 'category' ) ) {
		$posted_in = __( 'This entry was posted in %1$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'county_ext' );
	} else {
		$posted_in = __( 'Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'county_ext' );
	}
	// Prints the string, replacing the placeholders.
	printf(
		$posted_in,
		get_the_category_list( ', ' ),
		$tag_list,
		get_permalink(),
		the_title_attribute( 'echo=0' )
	);
}
endif;

// 1. Custom Post Type Registration (Events)

add_action( 'init', 'create_event_postype' );

function create_event_postype() {

$labels = array(
    'name' => _x('Events', 'post type general name'),
    'singular_name' => _x('Event', 'post type singular name'),
    'add_new' => _x('Add New', 'events'),
    'add_new_item' => __('Add New Event'),
    'edit_item' => __('Edit Event'),
    'new_item' => __('New Event'),
    'view_item' => __('View Event'),
    'search_items' => __('Search Events'),
    'not_found' =>  __('No events found'),
    'not_found_in_trash' => __('No events found in Trash'),
    'parent_item_colon' => '',
);

$args = array(
    'label' => __('Events'),
    'labels' => $labels,
    'public' => true,
    'can_export' => true,
    'show_ui' => true,
    '_builtin' => false,
    '_edit_link' => 'post.php?post=%d', // ?
    'capability_type' => 'post',
    'hierarchical' => false,
    'rewrite' => array( "slug" => "events" ),
    'supports'=> array('title', 'thumbnail', 'excerpt', 'editor') ,
    'show_in_nav_menus' => true,
    'taxonomies' => array( 'tf_eventcategory', 'post_tag')
);

register_post_type( 'tf_events', $args);

}

function create_eventcategory_taxonomy() {

$labels = array(
    'name' => _x( 'Categories', 'taxonomy general name' ),
    'singular_name' => _x( 'Category', 'taxonomy singular name' ),
    'search_items' =>  __( 'Search Categories' ),
    'popular_items' => __( 'Popular Categories' ),
    'all_items' => __( 'All Categories' ),
    'parent_item' => null,
    'parent_item_colon' => null,
    'edit_item' => __( 'Edit Category' ),
    'update_item' => __( 'Update Category' ),
    'add_new_item' => __( 'Add New Category' ),
    'new_item_name' => __( 'New Category Name' ),
    'separate_items_with_commas' => __( 'Separate categories with commas' ),
    'add_or_remove_items' => __( 'Add or remove categories' ),
    'choose_from_most_used' => __( 'Choose from the most used categories' ),
);

register_taxonomy('tf_eventcategory','tf_events', array(
    'label' => __('Event Category'),
    'labels' => $labels,
    'hierarchical' => true,
    'show_ui' => true,
    'query_var' => true,
    'rewrite' => array( 'slug' => 'event-category' ),
));
}

add_action( 'init', 'create_eventcategory_taxonomy', 0 );

// 3. Show Columns

add_filter ("manage_edit-tf_events_columns", "tf_events_edit_columns");
add_action ("manage_posts_custom_column", "tf_events_custom_columns");

function tf_events_edit_columns($columns) {

$columns = array(
    "cb" => "<input type=\"checkbox\" />",
    "tf_col_ev_cat" => "Category",
    "tf_col_ev_date" => "Dates",
    "tf_col_ev_times" => "Times",
    "tf_col_ev_thumb" => "Thumbnail",
    "title" => "Event",
    "tf_col_ev_desc" => "Description",
    );
return $columns;
}

function tf_events_custom_columns($column)
{
global $post;
$custom = get_post_custom();
switch ($column)
{
case "tf_col_ev_cat":
    // - show taxonomy terms -
    $eventcats = get_the_terms($post->ID, "tf_eventcategory");
    $eventcats_html = array();
    if ($eventcats) {
    foreach ($eventcats as $eventcat)
    array_push($eventcats_html, $eventcat->name);
    echo implode($eventcats_html, ", ");
    } else {
    _e('None', 'themeforce');;
    }
break;
case "tf_col_ev_date":
    // - show dates -
    $startd = $custom["tf_events_startdate"][0];
    $endd = $custom["tf_events_enddate"][0];
    $startdate = date("F j, Y", $startd);
    $enddate = date("F j, Y", $endd);
    echo $startdate . '<br /><em>' . $enddate . '</em>';
break;
case "tf_col_ev_times":
    // - show times -
    $startt = $custom["tf_events_startdate"][0];
    $endt = $custom["tf_events_enddate"][0];
    $time_format = get_option('time_format');
    $starttime = date($time_format, $startt);
    $endtime = date($time_format, $endt);
    echo $starttime . ' - ' .$endtime;
break;
case "tf_col_ev_thumb":
    // - show thumb -
    $post_image_id = get_post_thumbnail_id(get_the_ID());
    if ($post_image_id) {
    $thumbnail = wp_get_attachment_image_src( $post_image_id, 'post-thumbnail', false);
    if ($thumbnail) (string)$thumbnail = $thumbnail[0];
    echo '<img src="';
    echo bloginfo('template_url');
    echo '/timthumb/timthumb.php?src=';
    echo $thumbnail;
    echo '&h=60&w=60&zc=1" alt="" />';
}
break;
case "tf_col_ev_desc";
    the_excerpt();
break;

}
}

// 4. Show Meta-Box

add_action( 'admin_init', 'tf_events_create' );

function tf_events_create() {
    add_meta_box('tf_events_meta', 'Events', 'tf_events_meta', 'tf_events');
}

function tf_events_meta () {

// - grab data -

global $post;
$custom = get_post_custom($post->ID);
$meta_sd = $custom["tf_events_startdate"][0];
$meta_ed = $custom["tf_events_enddate"][0];
$meta_st = $meta_sd;
$meta_et = $meta_ed;

// - grab wp time format -

$date_format = get_option('date_format'); // Not required in my code
$time_format = get_option('time_format');

// - populate today if empty, 00:00 for time -

if ($meta_sd == null) { $meta_sd = time(); $meta_ed = $meta_sd; $meta_st = 0; $meta_et = 0;}

// - convert to pretty formats -

$clean_sd = date("D, M d, Y", $meta_sd);
$clean_ed = date("D, M d, Y", $meta_ed);
$clean_st = date($time_format, $meta_st);
$clean_et = date($time_format, $meta_et);

// - security -

echo '<input type="hidden" name="tf-events-nonce" id="tf-events-nonce" value="' .
wp_create_nonce( 'tf-events-nonce' ) . '" />';

// - output -

?>
<div class="tf-meta">
<ul>
    <li><label>Start Date</label><input name="tf_events_startdate" class="tfdate" value="<?php echo $clean_sd; ?>" /></li>
    <li><label>Start Time</label><input name="tf_events_starttime" value="<?php echo $clean_st; ?>" /><em>Use 24h format (7pm = 19:00)</em></li>
    <li><label>End Date</label><input name="tf_events_enddate" class="tfdate" value="<?php echo $clean_ed; ?>" /></li>
    <li><label>End Time</label><input name="tf_events_endtime" value="<?php echo $clean_et; ?>" /><em>Use 24h format (7pm = 19:00)</em></li>
</ul>
</div>
<?php
}







// Admin Menus
// -----------------------------------------------------------------------------
// make the options user-selectable

/* put stuff on pages and init-frontend */
if (!class_exists("AgriLifeCounties")) {
  
  class AgriLifeCounties {
	var $adminOptionsName = "AgrilifeCountyOptions";
	public $countyArray = array(
		0 => '',
		1 => 'Anderson',
		3 => 'Andrews',
		5 => 'Angelina',
		7 => 'Aransas',
		9 => 'Archer',
		11 => 'Armstrong',
		13 => 'Atascosa',
		15 => 'Austin',
		17 => 'Bailey',
		19 => 'Bandera',
		21 => 'Bastrop',
		23 => 'Baylor',
		25 => 'Bee',
		27 => 'Bell',
		29 => 'Bexar',
		31 => 'Blanco',
		33 => 'Borden',
		35 => 'Bosque',
		37 => 'Bowie',
		39 => 'Brazoria',
		41 => 'Brazos',
		43 => 'Brewster',
		45 => 'Briscoe',
		47 => 'Brooks',
		49 => 'Brown',
		51 => 'Burleson',
		53 => 'Burnet',
		55 => 'Caldwell',
		57 => 'Calhoun',
		59 => 'Callahan',
		61 => 'Cameron',
		63 => 'Camp',
		65 => 'Carson',
		67 => 'Cass',
		69 => 'Castro',
		71 => 'Chambers',
		73 => 'Cherokee',
		75 => 'Childress',
		77 => 'Clay',
		79 => 'Cochran',
		81 => 'Coke',
		83 => 'Coleman',
		85 => 'Collin',
		87 => 'Collingsworth',
		89 => 'Colorado',
		91 => 'Comal',
		93 => 'Comanche',
		95 => 'Concho',
		97 => 'Cooke',
		99 => 'Coryell',
		101 => 'Cottle',
		103 => 'Crane',
		105 => 'Crockett',
		107 => 'Crosby',
		109 => 'Culberson',
		111 => 'Dallam',
		113 => 'Dallas',
		115 => 'Dawson',
		117 => 'Deaf Smith',
		119 => 'Delta',
		121 => 'Denton',
		123 => 'DeWitt',
		125 => 'Dickens',
		127 => 'Dimmit',
		129 => 'Donley',
		131 => 'Duval',
		133 => 'Eastland',
		135 => 'Ector',
		137 => 'Edwards',
		139 => 'Ellis',
		141 => 'El Paso',
		143 => 'Erath',
		145 => 'Falls',
		147 => 'Fannin',
		149 => 'Fayette',
		151 => 'Fisher',
		153 => 'Floyd',
		155 => 'Foard',
		157 => 'Fort Bend',
		159 => 'Franklin',
		161 => 'Freestone',
		163 => 'Frio',
		165 => 'Gaines',
		167 => 'Galveston',
		169 => 'Garza',
		171 => 'Gillespie',
		173 => 'Glasscock',
		175 => 'Goliad',
		177 => 'Gonzales',
		179 => 'Gray',
		181 => 'Grayson',
		183 => 'Gregg',
		185 => 'Grimes',
		187 => 'Guadalupe',
		189 => 'Hale',
		191 => 'Hall',
		193 => 'Hamilton',
		195 => 'Hansford',
		197 => 'Hardeman',
		199 => 'Hardin',
		201 => 'Harris',
		203 => 'Harrison',
		205 => 'Hartley',
		207 => 'Haskell',
		209 => 'Hays',
		211 => 'Hemphill',
		213 => 'Henderson',
		215 => 'Hidalgo',
		217 => 'Hill',
		219 => 'Hockley',
		221 => 'Hood',
		223 => 'Hopkins',
		225 => 'Houston',
		227 => 'Howard',
		229 => 'Hudspeth',
		231 => 'Hunt',
		233 => 'Hutchinson',
		235 => 'Irion',
		237 => 'Jack',
		239 => 'Jackson',
		241 => 'Jasper',
		243 => 'Jeff Davis',
		245 => 'Jefferson',
		247 => 'Jim Hogg',
		249 => 'Jim Wells',
		251 => 'Johnson',
		253 => 'Jones',
		255 => 'Karnes',
		257 => 'Kaufman',
		259 => 'Kendall',
		261 => 'Kenedy',
		263 => 'Kent',
		265 => 'Kerr',
		267 => 'Kimble',
		269 => 'King',
		271 => 'Kinney',
		273 => 'Kleberg',
		275 => 'Knox',
		277 => 'Lamar',
		279 => 'Lamb',
		281 => 'Lampasas',
		283 => 'La Salle',
		285 => 'Lavaca',
		287 => 'Lee',
		289 => 'Leon',
		291 => 'Liberty',
		293 => 'Limestone',
		295 => 'Lipscomb',
		297 => 'Live Oak',
		299 => 'Llano',
		301 => 'Loving',
		303 => 'Lubbock',
		305 => 'Lynn',
		307 => 'McCulloch',
		309 => 'McLennan',
		311 => 'McMullen',
		313 => 'Madison',
		315 => 'Marion',
		317 => 'Martin',
		319 => 'Mason',
		321 => 'Matagorda',
		323 => 'Maverick',
		325 => 'Medina',
		327 => 'Menard',
		329 => 'Midland',
		331 => 'Milam',
		333 => 'Mills',
		335 => 'Mitchell',
		337 => 'Montague',
		339 => 'Montgomery',
		341 => 'Moore',
		343 => 'Morris',
		345 => 'Motley',
		347 => 'Nacogdoches',
		349 => 'Navarro',
		351 => 'Newton',
		353 => 'Nolan',
		355 => 'Nueces',
		357 => 'Ochiltree',
		359 => 'Oldham',
		361 => 'Orange',
		363 => 'Palo Pinto',
		365 => 'Panola',
		367 => 'Parker',
		369 => 'Parmer',
		371 => 'Pecos',
		373 => 'Polk',
		375 => 'Potter',
		377 => 'Presidio',
		379 => 'Rains',
		381 => 'Randall',
		383 => 'Reagan',
		385 => 'Real',
		387 => 'Red River',
		389 => 'Reeves',
		391 => 'Refugio',
		393 => 'Roberts',
		395 => 'Robertson',
		397 => 'Rockwall',
		399 => 'Runnels',
		401 => 'Rusk',
		403 => 'Sabine',
		405 => 'San Augustine',
		407 => 'San Jacinto',
		409 => 'San Patricio',
		411 => 'San Saba',
		413 => 'Schleicher',
		415 => 'Scurry',
		417 => 'Shackelford',
		419 => 'Shelby',
		421 => 'Sherman',
		423 => 'Smith',
		425 => 'Somervell',
		427 => 'Starr',
		429 => 'Stephens',
		431 => 'Sterling',
		433 => 'Stonewall',
		435 => 'Sutton',
		437 => 'Swisher',
		439 => 'Tarrant',
		441 => 'Taylor',
		443 => 'Terrell',
		445 => 'Terry',
		447 => 'Throckmorton',
		449 => 'Titus',
		451 => 'Tom Green',
		453 => 'Travis',
		455 => 'Trinity',
		457 => 'Tyler',
		459 => 'Upshur',
		461 => 'Upton',
		463 => 'Uvalde',
		465 => 'Val Verde',
		467 => 'Van Zandt',
		469 => 'Victoria',
		471 => 'Walker',
		473 => 'Waller',
		475 => 'Ward',
		477 => 'Washington',
		479 => 'Webb',
		481 => 'Wharton',
		483 => 'Wheeler',
		485 => 'Wichita',
		487 => 'Wilbarger',
		489 => 'Willacy',
		491 => 'Williamson',
		493 => 'Wilson',
		495 => 'Winkler',
		497 => 'Wise',
		499 => 'Wood',
		501 => 'Yoakum',
		503 => 'Young',
		505 => 'Zapata',
		507 => 'Zavala');

	function AgriLifeCounties() { //constructor
	  
	} // End Constructor
	function init() {
		$this->getAdminOptions();
	}
	//Returns an array of admin options
	function getAdminOptions() {
		$agrilifeAdminOptions = array(
			'county-name' => '',
			'county-name-human' => '',
			'address-street1' => '',
			'address-street2' => '',
			'address-city' => '',
			'address-zip' => '',
			
			'address-mail-street1' => '',
			'address-mail-street2' => '',
			'address-mail-city' => '',
			'address-mail-zip' => '',
			
			'phone' => '',
			'fax' =>'',
			
			'feedBurner' => '',
			'googleAnalytics' => '');
		$agrilifeCountyOptions = get_option($this->adminOptionsName);
		if (!empty($agrilifeCountyOptions)) {
			foreach ($agrilifeCountyOptions as $key => $option)
				$agrilifeAdminOptions[$key] = $option;
		}				
		update_option($this->adminOptionsName, $agrilifeAdminOptions);
		return $agrilifeAdminOptions;
	}


	function set_defaults() {
	
	  $options = get_option('AgrilifeCountyOptions');
	  
	  //County Name Default
	  $options['county-name'] = '';
	  $options['county-name-human'] = '';
	  
	  //Address Defaults
	  $options['address-street1'] = '';
	  $options['address-street2'] = '';
	  $options['address-city'] = '';
	  $options['address-zip'] = '';

	  $options['address-mail-street1'] = '';
	  $options['address-mail-street2'] = '';
	  $options['address-mail-city'] = '';
	  $options['address-mail-zip'] = '';
	  
	  $options['phone'] = '';
	  $options['fax'] = '';
	
	  //Set Google Defaults
	  $options['feedBurner'] = '';
	  $options['googleAnalytics'] = '';
	  
  
	  update_option('AgrilifeCountyOptions',$options);
	}
	
	//Prints out the admin page
	function printAdminPage() {
		  $agrilifeCountyOptions = $this->getAdminOptions();
	     
		  	// On Submit
			if (isset($_POST['update_agrilifeSettings'])) {
				//Sanitize This Data

				//County Name Default
				if (isset($_POST['county-name'])) {
				  // County Integer
				  $agrilifeCountyOptions['county-name'] = $_POST['county-name'];
				  // County Name (Human-Readable)
				  $agrilifeCountyOptions['county-name-human'] = $this->countyArray[$_POST['county-name']];
				}

				

				//Address Defaults
				if (isset($_POST['address-street1'])) 
				  $agrilifeCountyOptions['address-street1'] = stripslashes(apply_filters('content_save_pre', $_POST['address-street1']));

				if (isset($_POST['address-street2'])) 
				  $agrilifeCountyOptions['address-street2'] = stripslashes(apply_filters('content_save_pre', $_POST['address-street2']));

				if (isset($_POST['address-city'])) 
				  $agrilifeCountyOptions['address-city'] = stripslashes(apply_filters('content_save_pre', $_POST['address-city']));

				if (isset($_POST['address-zip'])) 
				  $agrilifeCountyOptions['address-zip'] = stripslashes(apply_filters('content_save_pre', $_POST['address-zip']));


				if (isset($_POST['address-mail-street1'])) 
				  $agrilifeCountyOptions['address-mail-street1'] = stripslashes(apply_filters('content_save_pre', $_POST['address-mail-street1']));

				if (isset($_POST['address-mail-street2'])) 
				  $agrilifeCountyOptions['address-mail-street2'] = stripslashes(apply_filters('content_save_pre', $_POST['address-mail-street2']));

				if (isset($_POST['address-mail-city'])) 
				  $agrilifeCountyOptions['address-mail-city'] = stripslashes(apply_filters('content_save_pre', $_POST['address-mail-city']));

				if (isset($_POST['address-mail-zip'])) 
				  $agrilifeCountyOptions['address-mail-zip'] = stripslashes(apply_filters('content_save_pre', $_POST['address-mail-zip']));


				if (isset($_POST['phone'])) 
				  $agrilifeCountyOptions['phone'] = stripslashes(apply_filters('content_save_pre', $_POST['phone']));

				if (isset($_POST['fax'])) 
				  $agrilifeCountyOptions['fax'] = stripslashes(apply_filters('content_save_pre', $_POST['fax']));


				if (isset($_POST['feedBurner'])) 
				  $agrilifeCountyOptions['feedBurner'] = stripslashes(apply_filters('content_save_pre', $_POST['feedBurner'])); 
				if (isset($_POST['googleAnalytics'])) 
				  $agrilifeCountyOptions['googleAnalytics'] = stripslashes(apply_filters('content_save_pre', $_POST['googleAnalytics'])); 

				update_option($this->adminOptionsName, $agrilifeCountyOptions);

				?>
				<div class="updated"><p><strong><?php _e("Settings Updated.", "AgriLifeCounties");?></strong></p></div>
			<?php
			} //End On Submit Actions

?>
          
          
<div class="wrap">
<form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">
<h2>AgriLife County Site Configuration</h2>

 
<h3>County Information</h3>
<table class="form-table">
	<tr valign="top"> 
		<th scope="row">County Name</th> 
		<td>
            <select name="county-name">
			<?php
			//Make A County Dropdown
			foreach ($this->countyArray as $i => $value) {
				$selected = ($i==$agrilifeCountyOptions['county-name'] ? 'selected' : '');
			    echo '<option value="'.$i.'" '.$selected.'>'.$this->countyArray[$i].'</option>';
			}
			?>
			</select>
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">Phone</th> 
		<td>
            <input type="text" name="phone" id="phone" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['phone']; ?>" />
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">Fax</th> 
		<td>
            <input type="text" name="fax" id="fax" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['fax']; ?>" />
		</td>
	</tr>
</table>


<h3>Address</h3>
<h4>Physical</h4>
<table class="form-table">
	<tr valign="top"> 
		<th scope="row">Street 1</th> 
		<td>
            <input type="text" name="address-street1" id="address-street1" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['address-street1']; ?>" />
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">Street 2</th> 
		<td>
            <input type="text" name="address-street2" id="address-street2" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['address-street2']; ?>" />
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">City</th> 
		<td>
            <input type="text" name="address-city" id="address-city" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['address-city']; ?>" />
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">Zip</th> 
		<td>
            <input type="text" name="address-zip" id="address-zip" class="regular-text" maxlength="10" value="<?php echo $agrilifeCountyOptions['address-zip']; ?>" />
		</td>
	</tr>
</table>
<h4>Mailing (optional)</h4>
<table class="form-table">
	<tr valign="top"> 
		<th scope="row">Street 1</th> 
		<td>
            <input type="text" name="address-mail-street1" id="address-mail-street1" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['address-mail-street1']; ?>" />
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">Street 2</th> 
		<td>
            <input type="text" name="address-mail-street2" id="address-mail-street2" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['address-mail-street2']; ?>" />
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">City</th> 
		<td>
            <input type="text" name="address-mail-city" id="address-mail-city" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['address-mail-city']; ?>" />
		</td>
	</tr>
	<tr valign="top"> 
		<th scope="row">Zip</th> 
		<td>
            <input type="text" name="address-mail-zip" id="address-mail-zip" class="regular-text" maxlength="10" value="<?php echo $agrilifeCountyOptions['address-mail-zip']; ?>" />
		</td>
	</tr>
</table>

<h3 style="padding-top: 20px;"><?php _e('Google Analytics Settings') ?></h3> 
<table class="form-table">
	<tr valign="top"> 
		<th scope="row"><?php _e('Tracking Code') ?></th> 
		<td>
            <input type="text" name="googleAnalytics" id="googleAnalytics" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['googleAnalytics']; ?>" />
			<br />
			<?php _e('Ex: UA-XXXXX-2') ?>
		</td>
	</tr>
</table>


<a href="javascript:void(0);" onclick="jQuery(this).next('div').toggle();"><?php _e("What's Google Analytics? How do I set this up?") ?></a> 
    <div style="display:none; padding:10px 20px 20px; border:1px solid #CCC; "> 
	<p><?php _e("<a href=\"https://www.google.com/analytics/\">Google Analytics</a> is the free stats tracking system supplied by Google and produces very attractive (and comprehensive) stats.") ?></p>
	<p><?php _e("To get going, just <a href=\"http://www.google.com/analytics/sign_up.html\">sign up for Analytics</a>, set up a new account and copy the tracking code you receive (it'll start with 'UA-') into the box above and press 'Save' - it can take several hours before you see any stats, but once it is you've got access to one heck of a lot of data!") ?></p>
	<p><?php _e("For more information on finding the tracking code, please visit <a href=\"http://www.google.com/support/analytics/bin/answer.py?hl=en&amp;answer=55603\">this Google help site</a>.") ?></p>
	</div>

<h3><?php _e('Feedburner Settings') ?></h3> 
<table class="form-table">
	<tr valign="top"> 
		<th scope="row"><?php _e('FeedBurner Feed Address') ?></th> 
		<td>
            <input type="text" name="feedBurner" id="feedBurner" class="regular-text" maxlength="200" value="<?php echo $agrilifeCountyOptions['feedBurner']; ?>" />
			<br />
			<?php _e('Ex: http://feeds.feedburner.com/AgriLife') ?>
		</td>
	</tr>
</table>


<div class="submit">
<input type="submit" name="update_agrilifeSettings" value="<?php _e('Update Settings', 'AgriLifeCounties') ?>" /></div>
</form>
</div>

		  <?php
	  }//End function printAdminPage()
  }
} //End Class AgriLifeCounties



if (class_exists("AgriLifeCounties")) {
  $agrilife_customizer = new AgriLifeCounties();
  $options	= get_option('AgrilifeCountyOptions');

  //if db not already populated, the add defaults
  if (!is_array($options))
	  $agrilife_customizer->set_defaults();

}

//Initialize the admin panel
if (!function_exists("AgrilifeCustomize_ap")) {
	function AgrilifeCustomize_ap() {
		global $agrilife_customizer;
		if (!isset($agrilife_customizer)) {
			return;
		}
		if (function_exists('add_options_page')) {
			add_options_page('AgriLife County Site Configuration', 'County Config.', 9, 'agrilife-county-config-admin', array(&$agrilife_customizer, 'printAdminPage'));
		}
	}	
}

if (isset($agrilife_customizer)) {
	// put county options in admin menu
	add_action('admin_menu', 'AgrilifeCustomize_ap');
	
}




/**
 * Widget: Watch, Read, Listen
 * Three widgets in one with thoughtful defaults in case of absentee user.
 */

class WatchReadListenWidget extends WP_Widget {
	function WatchReadListenWidget() {
	//Constructor
		$widget_ops = array('classname' => 'widget Watch Read Listen', 'description' => 'Pick a YouTube Video and a Podcast RSS feed. *coming soon* AgriLife Bookstore Items' );
		$this->WP_Widget('WatchReadListenWidget', 'AgriLife: Watch, Read, Listen', $widget_ops);
	}

	function widget($args, $instance) {
	// Set YouTube Default
	$youtube_video_default = 'http://www.youtube.com/watch?v=Ly_yfmeR8s8';
	// Set Podcast Default
	$podcast_link_default  = 'http://tmnpodcast.libsyn.com/rss';
	// prints the widget
		if ( isset($instance['error']) && $instance['error'] )
			return;
		extract($args, EXTR_SKIP);
		
		
		// YouTube Processing
 		$user_video = empty($instance['youtube_video']) ? $youtube_video_default : apply_filters('widget_youtube_video', $instance['youtube_video']);
 		// If a URL was passed
		if ( 'http://' == substr( $user_video, 0, 7 ) ) {
			// Playlist URL
			if ( FALSE !== stristr( $user_video, 'view_play_list' ) ) {
				preg_match( '#http://(www.youtube|youtube|[A-Za-z]{2}.youtube)\.com/view_play_list\?p=([\w-]+)(.*?)#i', $user_video, $matches );
				if ( empty($matches) || empty($matches[2]) ) return $this->error( sprintf('Unable to parse URL, check for correct %s format', __('YouTube') ) );
				$embedpath = 'p/' . $matches[2];
				$fallbacklink = $fallbackcontent = 'http://www.youtube.com/view_play_list?p=' . $matches[2];
			}
			// Normal video URL
			else {
				preg_match( '#http://(www.youtube|youtube|[A-Za-z]{2}.youtube)\.com/(watch\?v=|w/\?v=|\?v=)([\w-]+)(.*?)#i', $user_video, $matches );
				if ( empty($matches) || empty($matches[3]) ) return $this->error( sprintf('Unable to parse URL, check for correct %s format', __('YouTube') ) );

				$embedpath = 'v/' . $matches[3];
				$fallbacklink = 'http://www.youtube.com/watch?v=' . $matches[3];
				$fallbackcontent = '<img src="http://img.youtube.com/vi/' . $matches[3] . '/0.jpg" alt="' . __('YouTube Preview Image', 'vipers-video-quicktags') . '" />';
			}
		}
		// If a URL wasn't passed, assume a video ID was passed instead
		else {
			$embedpath = 'v/' . $user_video;
			$fallbacklink = 'http://www.youtube.com/watch?v=' . $user_video;
			$fallbackcontent = '<img src="http://img.youtube.com/vi/' . $user_video . '/0.jpg" alt="' . __('YouTube Preview Image', 'vipers-video-quicktags') . '" />';
		}
		
		$youtube_video = 'http://www.youtube.com/' . $embedpath;

 		
 		// Podcast Processing
 		$podcast_link = empty($instance['podcast_link']) ? $podcast_link_default : apply_filters('widget_podcast_link', $instance['podcast_link']);
		$rss = fetch_feed($podcast_link);
		if ( ! is_wp_error($rss) ) {
			$podcast_desc = esc_attr(strip_tags(@html_entity_decode($rss->get_description(), ENT_QUOTES, get_option('blog_charset'))));
			$podcast_title= esc_attr(strip_tags(@html_entity_decode($rss->get_title(), ENT_QUOTES, get_option('blog_charset'))));
			$podcast_link_audio= esc_attr(strip_tags(@html_entity_decode($rss->get_link(), ENT_QUOTES, get_option('blog_charset'))));
			if ( empty($title) )
				$title = esc_html(strip_tags($rss->get_title()));
			$link = esc_url(strip_tags($rss->get_permalink()));
			while ( stristr($link, 'http') != $link )
				$link = substr($link, 1);
			$podcast_site_link = $link;
		}
		
		echo $before_widget;
		 ?>
		 
<div id="watchreadlisten-bg" class="widget">
	<div id="tabs">	
	<ul>
		<li><a href="#tabs-1">Watch</a></li>
		<li><a href="#tabs-2">Read</a></li>
		<li><a href="#tabs-3">Listen</a></li>
	</ul>
		<div id="tabs-1">
		<?php // Watch Tab ?>
		<object width="348" height="221">
			<param name="movie" value="<?php echo $youtube_video;?>"></param>
			<param name="allowFullScreen" value="true"></param>
			<param name="allowscriptaccess" value="always"></param>
			<embed src="<?php echo $youtube_video;?>" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="348" height="221"></embed></object>	
		<?php // END Watch Tab ?>		
		</div>
		<div id="tabs-2">		
			<?php // Read Tab ?>
			<ul class="books">
				<li>
					<a href="https://agrilifebookstore.org/publications_details.cfm?whichpublication=2423">
					<dl>
						<dt class="book-title">Brush &amp; Weeds</dt>	
						<dd class="book-cover"><img class="book" src="http://brazos.agrilife.org/wp-content/themes/county/images/brush-weeds-cover.png" /></dd>
						<dd class="price"><em>$</em>19<span>99</span></dd>	
					</dl>
					</a>
					<p class="buy btn"><a href="https://agrilifebookstore.org/publications_details.cfm?whichpublication=2423">Buy</a></p>					
				</li>
				<li>	
					<a href="https://agrilifebookstore.org/publications_details.cfm?whichpublication=1979">
					<dl>
						<dt class="book-title">Rainwater Harvest</dt>	
						<dd class="book-cover"><img class="book" src="http://brazos.agrilife.org/wp-content/themes/county/images/rainwater-harvest-cover.png" /></dd>
						<dd class="price"><em></em>Free<span></span></dd>						
					</dl>
					</a>
					<p class="buy btn"><a href="https://agrilifebookstore.org/publications_details.cfm?whichpublication=1979">Read</a></p>					
				</li>
			</ul>
			<?php // END Read Tab ?>
			</div>		
		<div id="tabs-3">
			<?php // Listen Tab ?>
			<h4><a href="<?php echo $podcast_site_link;?>"><?php echo $podcast_title;?></a></h4>
			<?php wp_widget_rss_podcast_output( $rss, $instance ); ?>
		
			<!--<p><?php echo $podcast_desc;?></p>-->
			<?php // END Listen Tab ?>
		</div>
	
		
	</div>							
	</div>
				<?php 
	echo $after_widget;
	}

	function update($new_instance, $old_instance) {
	//save the widget
		$instance = $old_instance;
		$instance['youtube_video'] = strip_tags($new_instance['youtube_video']);
		$instance['podcast_link'] = strip_tags($new_instance['podcast_link']);
		return $instance;

	}

	function form($instance) {
	//widgetform in backend
		$instance = wp_parse_args( (array) $instance, array('youtube_video' => '', 'podcast_link' => '' ) );
		$youtube_video = strip_tags($instance['youtube_video']);
		$podcast_link = strip_tags($instance['podcast_link']);

?>
<p>
  <label for="<?php echo $this->get_field_id('youtube_video'); ?>">YouTube Video Link: <br /><code>http://www.youtube.com/watch?v=iRbX2uPgGsw</code>
  <input class="widefat" id="<?php echo $this->get_field_id('youtube_video'); ?>" name="<?php echo $this->get_field_name('youtube_video'); ?>" type="text" value="<?php echo attribute_escape($youtube_video); ?>" />
  </label>
</p>
<p>
  <label for="<?php echo $this->get_field_id('podcast_link'); ?>">Podcast Link: <br /><code>http://tmnpodcast.libsyn.com/rss</code>
  <input class="widefat" id="<?php echo $this->get_field_id('podcast_link'); ?>" name="<?php echo $this->get_field_name('podcast_link'); ?>" type="text" value="<?php echo attribute_escape($podcast_link); ?>" />
  </label>
</p>
<?php
	}

}

register_widget('WatchReadListenWidget');




/**
 * Display the RSS podcast entries in a list of html5 .
 *
 * @since 2.5.0
 *
 * @param string|array|object $rss RSS url.
 * @param array $args Widget arguments.
 */
function wp_widget_rss_podcast_output( $rss, $args = array() ) {
	if ( is_string( $rss ) ) {
		$rss = fetch_feed($rss);
	} elseif ( is_array($rss) && isset($rss['url']) ) {
		$args = $rss;
		$rss = fetch_feed($rss['url']);
	} elseif ( !is_object($rss) ) {
		return;
	}

	if ( is_wp_error($rss) ) {
		if ( is_admin() || current_user_can('manage_options') )
			echo '<p>' . sprintf( __('<strong>RSS Error</strong>: %s'), $rss->get_error_message() ) . '</p>';
		return;
	}

	$default_args = array( 'show_author' => 0, 'show_date' => 0, 'show_summary' => 0 );
	$args = wp_parse_args( $args, $default_args );
	extract( $args, EXTR_SKIP );

	$items = (int) $items;
	if ( $items < 1 || 20 < $items )
		$items = 10;
	$show_summary  = (int) $show_summary;
	$show_author   = (int) $show_author;
	$show_date     = (int) $show_date;

	if ( !$rss->get_item_quantity() ) {
		echo '<ul><li>' . __( 'An error has occurred; the feed is probably down. Try again later.' ) . '</li></ul>';
		$rss->__destruct();
		unset($rss);
		return;
	}

	echo '<ul>';
	foreach ( $rss->get_items(0, $items) as $item ) {
		$link = $item->get_link();
		while ( stristr($link, 'http') != $link )
			$link = substr($link, 1);
		$link = esc_url(strip_tags($link));
		$title = esc_attr(strip_tags($item->get_title()));
		if ( empty($title) )
			$title = __('Untitled');

		$desc = str_replace( array("\n", "\r"), ' ', esc_attr( strip_tags( @html_entity_decode( $item->get_description(), ENT_QUOTES, get_option('blog_charset') ) ) ) );
		$desc = wp_html_excerpt( $desc, 360 );

		// Append ellipsis. Change existing [...] to [&hellip;].
		if ( '[...]' == substr( $desc, -5 ) )
			$desc = substr( $desc, 0, -5 ) . '[&hellip;]';
		elseif ( '[&hellip;]' != substr( $desc, -10 ) )
			$desc .= ' [&hellip;]';

		$desc = esc_html( $desc );

		if ( $show_summary ) {
			$summary = "<div class='rssSummary'>$desc</div>";
		} else {
			$summary = '';
		}

		/*
		$date = '';
		if ( $show_date ) {
			$date = $item->get_date( 'U' );

			if ( $date ) {
				$date = ' <span class="rss-date">' . date_i18n( get_option( 'date_format' ), $date ) . '</span>';
			}
		}

		$author = '';
		if ( $show_author ) {
			$author = $item->get_author();
			if ( is_object($author) ) {
				$author = $author->get_name();
				$author = ' <cite>' . esc_html( strip_tags( $author ) ) . '</cite>';
			}
		}
		if ( $link == '' ) {
			echo "<li>$title{$date}{$summary}{$author}";
		} else {
			echo "<li><a class='rsswidget' href='$link' title='$desc'>$title</a>{$date}{$summary}{$author}";
		}
		*/
	  
		if ($enclosure = $item->get_enclosure())
		{
			echo "<li><embed type=\"application/x-shockwave-flash\" flashvars=\"audioUrl=".$enclosure->get_link()."\" src=\"http://www.google.com/reader/ui/3523697345-audio-player.swf\" width=\"400\" height=\"27\" quality=\"best\"></embed></li>";
			//echo "<li><audio src=\"".$enclosure->get_link()."\"> controls preload=\"none\">Your browser does not support the audio element.</audio></li>";
			//echo "<li><a class='rsswidget' href='".."' title='$desc'>$title</a></li>";
		}
		
	}
	echo '</ul>';
	$rss->__destruct();
	unset($rss);
}





















/**
 * Change Default Role Permissions
 * For more info about the options available visit: http://codex.wordpress.org/Roles_and_Capabilities
 */


/**
 * Add new permissions/capabilities to a specific role
 *
 * @param string $role
 * @param string $cap
 */
function add_capability($role,$cap) {
	$role_obj = get_role($role); // get the the role object
	$role_obj->add_cap($cap); // add $cap capability to this role object
}
//add_capability('subscriber','read_private_pages'); //Example

/**
 * Remove existing permissions/capabilities to a specific role
 *
 * @param string $role
 * @param string $cap
 */
function remove_capability($role,$cap) {
	$role_obj = get_role($role); // get the the role object
	$role_obj->remove_cap($cap); // add $cap capability to this role object
}
//remove_capability('subscriber','read_private_pages'); //Example


add_capability('editor','edit_theme_options');


// Brute-force Remove Tools Menu
function remove_menus () {
global $menu;
	if( (current_user_can('moderate_comments')) ) { $restricted = array(__('Tools'),  __('Media'),  __('Comments')); } // check if moderator or less and hide 

	//$restricted = array(__('Dashboard'), __('Posts'), __('Media'), __('Links'), __('Pages'), __('Appearance'), __('Tools'), __('Users'), __('Settings'), __('Comments'), __('Plugins'));
	end ($menu);
	while (prev($menu)){
		$value = explode(' ',$menu[key($menu)][0]);
		if(in_array($value[0] != NULL?$value[0]:"" , $restricted)){unset($menu[key($menu)]);}
	}
}
add_action('admin_menu', 'remove_menus');



/* new 3.1 style 
add_action( 'admin_init', 'my_remove_menu_pages' );

function my_remove_menu_pages() {
	if( (current_user_can('moderate_comments')) ) {
		remove_menu_page('edit-comments.php');
		remove_menu_page('tools.php');	
		remove_menu_page('upload.php');
	}
}
*/